//! DAI (MakerDAO) Stablecoin Implementation
//!
//! DAI is a decentralized stablecoin generated by the Maker Protocol.
//! Uses 18 decimals on all chains.

use async_trait::async_trait;
use ethers::types::{Address, U256};
use ramp_common::{Error, Result};
use std::collections::HashMap;

use super::{Stablecoin, StablecoinMetadata, TxHash};

/// DAI Token implementation
pub struct DaiToken {
    /// Chain ID -> Contract Address mapping
    contracts: HashMap<u64, Address>,
}

impl Default for DaiToken {
    fn default() -> Self {
        Self::new()
    }
}

impl DaiToken {
    /// Create a new DAI token with known contract addresses
    pub fn new() -> Self {
        let mut contracts = HashMap::new();

        // Ethereum Mainnet
        if let Ok(addr) = "0x6B175474E89094C44Da98b954EesdfDCfE7E2aFce27".parse::<Address>() {
            contracts.insert(1, addr);
        } else if let Ok(addr) = "0x6B175474E89094C44Da98b954EesdfDCfE7E2aFce27"
            .replace("sdf", "")
            .parse::<Address>()
        {
            // Correct address: 0x6B175474E89094C44Da98b954EedfDCfE7E2aFce27
            contracts.insert(1, addr);
        }
        // Use the correct Ethereum DAI address
        if let Ok(addr) = "0x6B175474E89094C44Da98b954EedfDCfE7E2aFce27".parse() {
            contracts.insert(1, addr);
        }

        // Polygon
        if let Ok(addr) = "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063".parse() {
            contracts.insert(137, addr);
        }

        // BNB Chain
        if let Ok(addr) = "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3".parse() {
            contracts.insert(56, addr);
        }

        // Arbitrum One
        if let Ok(addr) = "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1".parse() {
            contracts.insert(42161, addr);
        }

        // Optimism
        if let Ok(addr) = "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1".parse() {
            contracts.insert(10, addr);
        }

        // Avalanche C-Chain
        if let Ok(addr) = "0xd586E7F844cEa2F87f50152665BCbc2C279D8d70".parse() {
            contracts.insert(43114, addr);
        }

        // Base
        if let Ok(addr) = "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb".parse() {
            contracts.insert(8453, addr);
        }

        Self { contracts }
    }

    /// Add a custom contract address for a chain
    pub fn with_contract(mut self, chain_id: u64, address: Address) -> Self {
        self.contracts.insert(chain_id, address);
        self
    }
}

#[async_trait]
impl Stablecoin for DaiToken {
    fn symbol(&self) -> &str {
        "DAI"
    }

    fn name(&self) -> &str {
        "Dai Stablecoin"
    }

    fn decimals(&self) -> u8 {
        18 // DAI uses 18 decimals, unlike USDT/USDC
    }

    fn metadata(&self) -> StablecoinMetadata {
        StablecoinMetadata {
            symbol: "DAI".to_string(),
            name: "Dai Stablecoin".to_string(),
            decimals: 18,
            logo_url: Some("https://assets.coingecko.com/coins/images/9956/large/Badge_Dai.png".to_string()),
            website: Some("https://makerdao.com".to_string()),
            description: Some("DAI is a decentralized stablecoin soft-pegged to USD".to_string()),
        }
    }

    fn contract_address(&self, chain_id: u64) -> Option<Address> {
        self.contracts.get(&chain_id).copied()
    }

    fn supported_chains(&self) -> Vec<u64> {
        self.contracts.keys().copied().collect()
    }

    async fn balance_of(&self, chain_id: u64, address: Address) -> Result<U256> {
        let _contract = self.contract_address(chain_id).ok_or_else(|| {
            Error::Validation(format!("DAI not supported on chain {}", chain_id))
        })?;

        tracing::debug!(
            chain_id = chain_id,
            address = %address,
            "Fetching DAI balance (mock)"
        );

        Ok(U256::zero())
    }

    async fn transfer(
        &self,
        chain_id: u64,
        from: Address,
        to: Address,
        amount: U256,
    ) -> Result<TxHash> {
        let contract = self.contract_address(chain_id).ok_or_else(|| {
            Error::Validation(format!("DAI not supported on chain {}", chain_id))
        })?;

        tracing::info!(
            chain_id = chain_id,
            contract = %contract,
            from = %from,
            to = %to,
            amount = %amount,
            "Initiating DAI transfer"
        );

        Err(Error::Validation(
            "DAI transfer not implemented - use SmartAccountService".to_string(),
        ))
    }

    async fn allowance(
        &self,
        chain_id: u64,
        owner: Address,
        spender: Address,
    ) -> Result<U256> {
        let _contract = self.contract_address(chain_id).ok_or_else(|| {
            Error::Validation(format!("DAI not supported on chain {}", chain_id))
        })?;

        tracing::debug!(
            chain_id = chain_id,
            owner = %owner,
            spender = %spender,
            "Checking DAI allowance (mock)"
        );

        Ok(U256::zero())
    }

    async fn approve(
        &self,
        chain_id: u64,
        owner: Address,
        spender: Address,
        amount: U256,
    ) -> Result<TxHash> {
        let contract = self.contract_address(chain_id).ok_or_else(|| {
            Error::Validation(format!("DAI not supported on chain {}", chain_id))
        })?;

        tracing::info!(
            chain_id = chain_id,
            contract = %contract,
            owner = %owner,
            spender = %spender,
            amount = %amount,
            "Approving DAI spending"
        );

        Err(Error::Validation(
            "DAI approve not implemented - use SmartAccountService".to_string(),
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_dai_metadata() {
        let dai = DaiToken::new();

        assert_eq!(dai.symbol(), "DAI");
        assert_eq!(dai.name(), "Dai Stablecoin");
        assert_eq!(dai.decimals(), 18); // DAI uses 18 decimals
    }

    #[test]
    fn test_dai_chain_support() {
        let dai = DaiToken::new();

        // DAI is widely available
        assert!(dai.is_supported_on_chain(137)); // Polygon
        assert!(dai.is_supported_on_chain(56)); // BSC
        assert!(dai.is_supported_on_chain(42161)); // Arbitrum
        assert!(!dai.is_supported_on_chain(999)); // Unknown chain
    }

    #[test]
    fn test_dai_decimal_difference() {
        let dai = DaiToken::new();

        // DAI uses 18 decimals, so 1 DAI = 10^18 base units
        // This is different from USDT/USDC which use 6 decimals
        assert_eq!(dai.decimals(), 18);

        // 1 DAI in base units
        let one_dai = U256::from(10u64).pow(U256::from(18u64));
        assert_eq!(one_dai, U256::from(1_000_000_000_000_000_000u64));
    }
}
