apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- nats-configmap.yaml
- secret.example.yaml
- rbac.yaml
- postgres-statefulset.yaml
- redis-statefulset.yaml
- nats-statefulset.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
- network-policy.yaml
- ../jobs/migration-job.yaml
